### ISSUE TITLE
[Question] What is the usage of setup.sh script in the ags config?

### ISSUE THREAD

**Issue by GeorgeAndreiBals** [kotontrion/dotfiles#2]
Hey, started learning ags (and by extension js/ts) earlier this week and I'm curious about the role of [setup.sh](https://github.com/kotontrion/dotfiles/blob/main/.config/ags/setup.sh).

**Comment by kotontrion** [comment]
This script generate the types for the LSP. See [here](https://github.com/Aylur/ags/wiki/typescript). 
The usage of this is optional, but having the types is useful. I probably should rename this to something like gen_types.sh

**Comment by GeorgeAndreiBals** [comment]
Ah, makes sense, thanks! Yeah, gen_types.sh should be more clear 😄  And another thing, I tried both your dotfiles and Aylurs' and I noticed that yours are on version 1 of AGS (I believe) and his are on 1.5.4. Does this matter?

**Comment by kotontrion** [comment]
I'm using the git version of ags, so currently version 1.5.5. the version in the package.json refers to the version of my dotfiles, but i guess I could edit them to have them match the used ags version.
I was planning on extending the readme to include more information anyway and the used ags version should be mentioned there as well then.

**Comment by GeorgeAndreiBals** [comment]
Thanks for the response!
