### ISSUE TITLE
another missing file

### ISSUE THREAD

**Issue by bawsdeep** [kotontrion/dotfiles#4]
.config/ags/node_modules/marked/lib/marked.esm.js 
apprearently missing in the current config

**Comment by kotontrion** [comment]
That is a library i use for parsing markdown, which is needed for the chatgpt widget.
This library is not included here. you have to run ` npm install`in .config/ags to install these dependencies, as described in the usage section in the readme.

**Comment by bawsdeep** [comment]
> That is a library i use for parsing markdown, which is needed for the chatgpt widget. This library is not included here. you have to run ` npm install`in .config/ags to install these dependencies, as described in the usage section in the readme.

i did run that im prett sure but ill try again later and give you some feedback

**Comment by bawsdeep** [comment]
alright  rerunning npm install resolved it thanks
